module.exports = function(grunt){
    grunt.initConfig({
        pkg:grunt.file.readJSON('package.json'),
        uglify:{
            options:{
                banner:'/*zyquan*/'
            },
            build:{
                src:'Scripts/product/test.js',
                dest:'dist/js/<%=pkg.name%>.min.js'
            }
        },
        cssmin:{
            options:{
                banner:'/*测试数据*/'
            },
            build:{
                src:'Content/product/*.css',
                dest:'dist/js/<%=pkg.name%>.min.css'
            }
        },
        jshint:{
            options:{

            },

        },
        postcss:{
            options:{
                processors:[
                    require('autoprefixer')
                ]
            },
            dist:{
                src:'Content/product/*.css'
            }
        },
        browserSync:{
            dev:{
                bsFiles:{
                    src:[
                        'Content/*/*.css',
                        'Views/*/*.html'
                    ],
                    options:{
                        watchTask:true,
                        server:'./'
                    }
                }
            }
        }
    });
    grunt.loadNpmTasks('grunt-contrib-uglify');
    grunt.loadNpmTasks('grunt-postcss');
    grunt.loadNpmTasks('grunt-browser-sync');
    grunt.loadNpmTasks('grunt-contrib-cssmin');
    grunt.loadNpmTasks('grunt-browser-sync');

    grunt.registerTask('default',['uglify','cssmin','postcss:dist']);

}
